# Data {#data}
For at arbejde med data skal de importeres ind i R. Det er simpelt, hvis de filer der skal importeres ligger i R’s aktive bibliotek. Det er en god ide at organisere dine data inden de importeres, hvilket der findes mange gode værktøjer til.

R kan importere fra de fleste formater, her vil jeg bruge; **CSV** og **Excel**

Du kan i RStudio vælge mellem at bruge den grafiske brugerflade (GUI) eller skrive den kode, du vil bruge til importen. 

## Grafisk (GUI)
Fordelen ved at bruge den grafiske brugerflade er, at du ikke skal huske de forskellige importfunktione. Det ligner lidt import i f.eks. Excel.

**Import af fra Excel**

Når du vil importere data fra en Excel fil, kan du bruge: File > Import Dataset > From Excel
Derefter vælger du den Excel fil, du vil importere 


## Kode
Excel import

```
salg <- read_excel("webinar_data.xlsx")                          # Indlæser første ark
salg <- read_excel("webinar_data.xlsx", sheet = "salgs_data")    # Indlæser arket salgs_data
salg <- read_excel("webinar_data.xlsx", sheet = 3)               # Indlæser ark 3
```
