# Plots {#plots}

## Standard plot

```
category <- table(salg$CategoryName)
str(category)
barplot(category[order(category, decreasing = T)])
```

Giver dette plot

``` {r echo = FALSE, results = FALSE, warning=FALSE, message=FALSE}
library(readxl)
salg <- read_excel("C:/Users/tuhe/Documents/GitHub/ida_r_intro_webinar/r_kode/webinar_data.xlsx", sheet = "salgs_data") 
category <- table(salg$CategoryName)
str(category)
barplot(category[order(category, decreasing = T)])
```


## ggplot2
Kode

```
ggplot(data=issalg) +
  geom_point(mapping = aes(x=Temperatur, y=Salg, color=Butik_Placering, size=Salg)) +
  geom_smooth(mapping = aes(x=Temperatur, y=Salg, color=Butik_Placering), se=FALSE) +
  geom_hline(yintercept = mean(issalg$Salg)) +
  annotate("text", label="Middel Salg", x=15, vjust = 0, y=mean(issalg$Salg+200)) +
  geom_vline(xintercept = mean(issalg$Temperatur)) +
  annotate("text", label="Middel Temperatur", y=100, hjust = 0, x=mean(issalg$Temperatur-0.5), angle = 90) +
  theme(panel.background = element_blank()) +
  theme(plot.background = element_blank()) +
  scale_x_continuous(name="Temperatur") +
  scale_y_continuous(name="Total Salg") +
  scale_color_discrete(name="Placering af butiken") +
  scale_size_continuous(name="Salg") +
  theme_classic()
```
Giver dette plot

```{r echo = FALSE, results = FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(readxl)
issalg <- read_excel("C:/Users/tuhe/Documents/GitHub/ida_r_intro_webinar/r_kode/webinar_data.xlsx", sheet = "issalg")

ggplot(data=issalg) +
  geom_point(mapping = aes(x=Temperatur, y=Salg, color=Butik_Placering, size=Salg)) +
  geom_smooth(mapping = aes(x=Temperatur, y=Salg, color=Butik_Placering), se=FALSE) +
  geom_hline(yintercept = mean(issalg$Salg)) +
  annotate("text", label="Middel Salg", x=15, vjust = 0, y=mean(issalg$Salg+200)) +
  geom_vline(xintercept = mean(issalg$Temperatur)) +
  annotate("text", label="Middel Temperatur", y=100, hjust = 0, x=mean(issalg$Temperatur-0.5), angle = 90) +
  theme(panel.background = element_blank()) +
  theme(plot.background = element_blank()) +
  scale_x_continuous(name="Temperatur") +
  scale_y_continuous(name="Total Salg") +
  scale_color_discrete(name="Placering af butiken") +
  scale_size_continuous(name="Salg") +
  theme_classic()
```

