# Demo Shiny {#shiny}
Når du har lavet en ”analyse” i R vil et tit være en fordel at kunne dele denne med andre, det kan du gøre ved at sende den dit R script og data, men det er nok ikke den mest brugervenlige måde.
En anden ulighed er vise det på en webside så det kan tilgås via en browser. Det kan du opnå via en R pakke der hedder shiny.
Du kan finde en del eksempler på løsninger oprettet i shiny her: <a href="https://shiny.rstudio.com/gallery/#demos" target="_blank">shiny.rstudio.com/gallery/#demos</a>

Det er også muligt at afvikle de 11 eksempler der følger med shiny på følgende måde:

```
# Shiny eksempler
runExample("01_hello")
runExample("02_text")
runExample("03_reactivity")
runExample("04_mpg")
runExample("05_sliders")
runExample("06_tabsets")
runExample("07_widgets")
runExample("08_html")
runExample("09_upload")
runExample("10_download")
runExample("11_timer")
```

## Struktur af en Shiny app
En Shimy App er ”samlet” i et enkelt script app.R som du kan afvikle.
app.R består af tre dele:

* Userinterface (ui.R) - *Her styrer du layout af din applikation*
* Server (server.R) - *Her definere du det der skal til for at opbygge din løsning*
* Kald til shinyApp function - *Her bygges selev løsningen*

Du kan oprette en ny shiny App under: 
**File – New File – Shiny Web App**
I dette vindue skal du indtaste navnet på din App og placeringen. Du har også mulighed for at vælge mellem og din App skal opdeles i to file, **ui.R** og **server.R**, eller om du vil have alt i en fil. 

Opdelingen i to filer giver dig de fleste muligheder og en bedre kontrol.

Du får to filer der indeholder en demo løsning som du kan bruge som 
udgangspunkt for din egen løsning.

